# config.yml

levels:
  levels-per-point: 20

perks:
  strength:
    minimum-level: 20

  speed:
    minimum-level: 40
    amount: 1.0

  health:
    minimum-level: 60
    amount: 2.0

  resistance:
    minimum-level: 80

  haste:
    minimum-level: 100

  reach:
    minimum-level: 120
    amount: 1.0