# plugin.yml

name: TpuPerks
version: 1.0.0
main: com.tpuperks.TpuPerks
api-version: '1.21'
author: Tpu
description: Sistema ligero de Perk Points y perks por niveles.

commands:
  tpu:
    description: Sistema de Perk Points
    usage: /tpu perks
    aliases: [tpup]

permissions:
  tpupersks.admin:
    description: Permite administrar los Perk Points
    default: op
